package org.telestion.mavlink.messages.mavlink.python_array_test;

import org.telestion.adapter.mavlink.annotation.MavField;
import org.telestion.adapter.mavlink.annotation.MavInfo;
import org.telestion.adapter.mavlink.annotation.NativeType;
import org.telestion.adapter.mavlink.annotation.MavArray;
import org.telestion.adapter.mavlink.message.MavlinkMessage;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Array test #7.</br>
 * </br>
 * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
 * 
 * @author Autogenerated by XML2Record-Tool (by Cedric Boes)
 * @version 1.0 (autogenerated)
 */
@MavInfo(id = 157, crc = 187)
@SuppressWarnings("preview")
public record ArrayTest7(
        /**
         * Value array</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavArray(length = 2)
        @MavField(nativeType = NativeType.DOUBLE)
        @JsonProperty int[] arD, 
        /**
         * Value array</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavArray(length = 2)
        @MavField(nativeType = NativeType.FLOAT)
        @JsonProperty int[] arF, 
        /**
         * Value array</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavArray(length = 2)
        @MavField(nativeType = NativeType.UINT_32)
        @JsonProperty int[] arU32, 
        /**
         * Value array</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavArray(length = 2)
        @MavField(nativeType = NativeType.INT_32)
        @JsonProperty int[] arI32, 
        /**
         * Value array</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavArray(length = 2)
        @MavField(nativeType = NativeType.UINT_16)
        @JsonProperty int[] arU16, 
        /**
         * Value array</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavArray(length = 2)
        @MavField(nativeType = NativeType.INT_16)
        @JsonProperty int[] arI16, 
        /**
         * Value array</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavArray(length = 2)
        @MavField(nativeType = NativeType.UINT_8)
        @JsonProperty int[] arU8, 
        /**
         * Value array</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavArray(length = 2)
        @MavField(nativeType = NativeType.INT_8)
        @JsonProperty int[] arI8, 
        /**
         * Value array</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavArray(length = 32)
        @MavField(nativeType = NativeType.CHAR)
        @JsonProperty int[] arC) implements MavlinkMessage {
    /**
     * There shall be no default-constructor for normal developers.
     */
    @SuppressWarnings("unused")
    private ArrayTest7() {
        this(null, null, null, null, null, null, null, null, null);
    }
}