package org.telestion.mavlink.messages.mavlink.test;

import org.telestion.adapter.mavlink.annotation.MavField;
import org.telestion.adapter.mavlink.annotation.MavInfo;
import org.telestion.adapter.mavlink.annotation.NativeType;
import org.telestion.adapter.mavlink.annotation.MavArray;
import org.telestion.adapter.mavlink.message.MavlinkMessage;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Test all field types</br>
 * </br>
 * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
 * 
 * @author Autogenerated by XML2Record-Tool (by Cedric Boes)
 * @version 1.0 (autogenerated)
 */
@MavInfo(id = 0, crc = 103)
@SuppressWarnings("preview")
public record TestTypes(
        /**
         * char</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.CHAR)
        @JsonProperty char c, 
        /**
         * string</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavArray(length = 10)
        @MavField(nativeType = NativeType.CHAR)
        @JsonProperty int[] s, 
        /**
         * uint8_t</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.UINT_8)
        @JsonProperty int u8, 
        /**
         * uint16_t</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.UINT_16)
        @JsonProperty int u16, 
        /**
         * uint32_t</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.UINT_32)
        @JsonProperty long u32, 
        /**
         * uint64_t</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.UINT_64)
        @JsonProperty long u64, 
        /**
         * int8_t</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.INT_8)
        @JsonProperty int s8, 
        /**
         * int16_t</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.INT_16)
        @JsonProperty int s16, 
        /**
         * int32_t</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.INT_32)
        @JsonProperty int s32, 
        /**
         * int64_t</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.INT_64)
        @JsonProperty long s64, 
        /**
         * float</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.FLOAT)
        @JsonProperty double f, 
        /**
         * double</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.DOUBLE)
        @JsonProperty double d, 
        /**
         * uint8_t_array</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavArray(length = 3)
        @MavField(nativeType = NativeType.UINT_8)
        @JsonProperty int[] u8Array, 
        /**
         * uint16_t_array</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavArray(length = 3)
        @MavField(nativeType = NativeType.UINT_16)
        @JsonProperty int[] u16Array, 
        /**
         * uint32_t_array</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavArray(length = 3)
        @MavField(nativeType = NativeType.UINT_32)
        @JsonProperty int[] u32Array, 
        /**
         * uint64_t_array</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavArray(length = 3)
        @MavField(nativeType = NativeType.UINT_64)
        @JsonProperty int[] u64Array, 
        /**
         * int8_t_array</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavArray(length = 3)
        @MavField(nativeType = NativeType.INT_8)
        @JsonProperty int[] s8Array, 
        /**
         * int16_t_array</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavArray(length = 3)
        @MavField(nativeType = NativeType.INT_16)
        @JsonProperty int[] s16Array, 
        /**
         * int32_t_array</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavArray(length = 3)
        @MavField(nativeType = NativeType.INT_32)
        @JsonProperty int[] s32Array, 
        /**
         * int64_t_array</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavArray(length = 3)
        @MavField(nativeType = NativeType.INT_64)
        @JsonProperty int[] s64Array, 
        /**
         * float_array</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavArray(length = 3)
        @MavField(nativeType = NativeType.FLOAT)
        @JsonProperty int[] fArray, 
        /**
         * double_array</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavArray(length = 3)
        @MavField(nativeType = NativeType.DOUBLE)
        @JsonProperty int[] dArray) implements MavlinkMessage {
    /**
     * There shall be no default-constructor for normal developers.
     */
    @SuppressWarnings("unused")
    private TestTypes() {
        this((char)0, null, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, null, null, null, null, null, null, null, null, null, null);
    }
}