package de.wuespace.telestion.example.periodicData;

import com.fasterxml.jackson.annotation.JsonProperty;
import de.wuespace.telestion.api.message.JsonMessage;

public record System_t(
		@JsonProperty long timeLocal,
		@JsonProperty byte stateCur,
		@JsonProperty double imuAccX,
		@JsonProperty double imuAccY,
		@JsonProperty double imuAccZ,
		@JsonProperty double imuGyroX,
		@JsonProperty double imuGyroY,
		@JsonProperty double imuGyroZ,
		@JsonProperty double baroPress,
		@JsonProperty double baroTemp,
		@JsonProperty double vacuumBaroPress,
		@JsonProperty double tachoRotRate,
		@JsonProperty byte[] servoAmps,
		@JsonProperty byte lidarServo,
		@JsonProperty byte[] batInfo,
		@JsonProperty byte[] systemVoltageInfo,
		@JsonProperty byte systemConfig,
		@JsonProperty double gpsLat,
		@JsonProperty double gpsLong,
		@JsonProperty byte gpsQuality,
		@JsonProperty byte gpsSatsUsed,
		@JsonProperty double gpsHdop,
		@JsonProperty double gpsAlt,
		@JsonProperty double filterVelVertical,
		@JsonProperty double filterHeightGround,
		@JsonProperty double filterRotorRotRate,
		@JsonProperty double filterBodyRotRate,
		@JsonProperty double filterVelVerticalInd,
		@JsonProperty double controllerBladePitch,
		@JsonProperty double controllerFinAngle,
		@JsonProperty byte controllerId,
		@JsonProperty byte availableStatus
) implements JsonMessage {
	private System_t() {
		this(
				0L,
				(byte) 0b0,
				.0,
				.0,
				.0,
				.0,
				.0,
				.0,
				.0,
				.0,
				.0,
				.0,
				new byte[]{},
				(byte) 0b0,
				new byte[]{},
				new byte[]{},
				(byte) 0b0,
				.0,
				.0,
				(byte) 0b0,
				(byte) 0b0,
				.0,
				.0,
				.0,
				.0,
				.0,
				.0,
				.0,
				.0,
				.0,
				(byte) 0b0,
				(byte) 0b0
		);
	}
}
