package org.telestion.mavlink.messages.mavlink.common;

import org.telestion.adapter.mavlink.annotation.MavField;
import org.telestion.adapter.mavlink.annotation.MavInfo;
import org.telestion.adapter.mavlink.annotation.NativeType;
import org.telestion.adapter.mavlink.annotation.MavArray;
import org.telestion.adapter.mavlink.message.MavlinkMessage;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The positioning status, as reported by GPS. This message is intended to display status information about each satellite visible to the receiver. See message GLOBAL_POSITION for the global position estimate. This message can contain information for up to 20 satellites.</br>
 * </br>
 * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
 * 
 * @author Autogenerated by XML2Record-Tool (by Cedric Boes)
 * @version 1.0 (autogenerated)
 */
@MavInfo(id = 25, crc = 23)
@SuppressWarnings("preview")
public record GpsStatus(
        /**
         * Number of satellites visible</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.UINT_8)
        @JsonProperty int satellitesVisible, 
        /**
         * Global satellite ID</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavArray(length = 20)
        @MavField(nativeType = NativeType.UINT_8)
        @JsonProperty int[] satellitePrn, 
        /**
         * 0: Satellite not used, 1: used for localization</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavArray(length = 20)
        @MavField(nativeType = NativeType.UINT_8)
        @JsonProperty int[] satelliteUsed, 
        /**
         * Elevation (0: right on top of receiver, 90: on the horizon) of satellite</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavArray(length = 20)
        @MavField(nativeType = NativeType.UINT_8)
        @JsonProperty int[] satelliteElevation, 
        /**
         * Direction of satellite, 0: 0 deg, 255: 360 deg.</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavArray(length = 20)
        @MavField(nativeType = NativeType.UINT_8)
        @JsonProperty int[] satelliteAzimuth, 
        /**
         * Signal to noise ratio of satellite</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavArray(length = 20)
        @MavField(nativeType = NativeType.UINT_8)
        @JsonProperty int[] satelliteSnr) implements MavlinkMessage {
    /**
     * There shall be no default-constructor for normal developers.
     */
    @SuppressWarnings("unused")
    private GpsStatus() {
        this(0, null, null, null, null, null);
    }
}