package org.telestion.mavlink.messages.mavlink.common;

import org.telestion.adapter.mavlink.annotation.MavField;
import org.telestion.adapter.mavlink.annotation.MavInfo;
import org.telestion.adapter.mavlink.annotation.NativeType;
import org.telestion.adapter.mavlink.annotation.MavArray;
import org.telestion.adapter.mavlink.message.MavlinkMessage;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Hardware status sent by an onboard computer.</br>
 * </br>
 * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
 * 
 * @author Autogenerated by XML2Record-Tool (by Cedric Boes)
 * @version 1.0 (autogenerated)
 * @deprecated This is still WIP and might change!
 */
@Deprecated
@MavInfo(id = 390, crc = 156)
@SuppressWarnings("preview")
public record OnboardComputerStatus(
        /**
         * Timestamp (UNIX Epoch time or time since system boot). The receiving end can infer timestamp format (since 1.1.1970 or since system boot) by checking for the magnitude of the number.</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.UINT_64)
        @JsonProperty long timeUsec, 
        /**
         * Time since system boot.</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.UINT_32)
        @JsonProperty long uptime, 
        /**
         * Type of the onboard computer: 0: Mission computer primary, 1: Mission computer backup 1, 2: Mission computer backup 2, 3: Compute node, 4-5: Compute spares, 6-9: Payload computers.</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.UINT_8)
        @JsonProperty int type, 
        /**
         * CPU usage on the component in percent (100 - idle). A value of UINT8_MAX implies the field is unused.</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavArray(length = 8)
        @MavField(nativeType = NativeType.UINT_8)
        @JsonProperty int[] cpuCores, 
        /**
         * Combined CPU usage as the last 10 slices of 100 MS (a histogram). This allows to identify spikes in load that max out the system, but only for a short amount of time. A value of UINT8_MAX implies the field is unused.</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavArray(length = 10)
        @MavField(nativeType = NativeType.UINT_8)
        @JsonProperty int[] cpuCombined, 
        /**
         * GPU usage on the component in percent (100 - idle). A value of UINT8_MAX implies the field is unused.</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavArray(length = 4)
        @MavField(nativeType = NativeType.UINT_8)
        @JsonProperty int[] gpuCores, 
        /**
         * Combined GPU usage as the last 10 slices of 100 MS (a histogram). This allows to identify spikes in load that max out the system, but only for a short amount of time. A value of UINT8_MAX implies the field is unused.</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavArray(length = 10)
        @MavField(nativeType = NativeType.UINT_8)
        @JsonProperty int[] gpuCombined, 
        /**
         * Temperature of the board. A value of INT8_MAX implies the field is unused.</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.INT_8)
        @JsonProperty int temperatureBoard, 
        /**
         * Temperature of the CPU core. A value of INT8_MAX implies the field is unused.</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavArray(length = 8)
        @MavField(nativeType = NativeType.INT_8)
        @JsonProperty int[] temperatureCore, 
        /**
         * Fan speeds. A value of INT16_MAX implies the field is unused.</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavArray(length = 4)
        @MavField(nativeType = NativeType.INT_16)
        @JsonProperty int[] fanSpeed, 
        /**
         * Amount of used RAM on the component system. A value of UINT32_MAX implies the field is unused.</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.UINT_32)
        @JsonProperty long ramUsage, 
        /**
         * Total amount of RAM on the component system. A value of UINT32_MAX implies the field is unused.</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.UINT_32)
        @JsonProperty long ramTotal, 
        /**
         * Storage type: 0: HDD, 1: SSD, 2: EMMC, 3: SD card (non-removable), 4: SD card (removable). A value of UINT32_MAX implies the field is unused.</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavArray(length = 4)
        @MavField(nativeType = NativeType.UINT_32)
        @JsonProperty int[] storageType, 
        /**
         * Amount of used storage space on the component system. A value of UINT32_MAX implies the field is unused.</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavArray(length = 4)
        @MavField(nativeType = NativeType.UINT_32)
        @JsonProperty int[] storageUsage, 
        /**
         * Total amount of storage space on the component system. A value of UINT32_MAX implies the field is unused.</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavArray(length = 4)
        @MavField(nativeType = NativeType.UINT_32)
        @JsonProperty int[] storageTotal, 
        /**
         * Link type: 0-9: UART, 10-19: Wired network, 20-29: Wifi, 30-39: Point-to-point proprietary, 40-49: Mesh proprietary</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavArray(length = 6)
        @MavField(nativeType = NativeType.UINT_32)
        @JsonProperty int[] linkType, 
        /**
         * Network traffic from the component system. A value of UINT32_MAX implies the field is unused.</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavArray(length = 6)
        @MavField(nativeType = NativeType.UINT_32)
        @JsonProperty int[] linkTxRate, 
        /**
         * Network traffic to the component system. A value of UINT32_MAX implies the field is unused.</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavArray(length = 6)
        @MavField(nativeType = NativeType.UINT_32)
        @JsonProperty int[] linkRxRate, 
        /**
         * Network capacity from the component system. A value of UINT32_MAX implies the field is unused.</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavArray(length = 6)
        @MavField(nativeType = NativeType.UINT_32)
        @JsonProperty int[] linkTxMax, 
        /**
         * Network capacity to the component system. A value of UINT32_MAX implies the field is unused.</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavArray(length = 6)
        @MavField(nativeType = NativeType.UINT_32)
        @JsonProperty int[] linkRxMax) implements MavlinkMessage {
    /**
     * There shall be no default-constructor for normal developers.
     */
    @SuppressWarnings("unused")
    private OnboardComputerStatus() {
        this(0, 0, 0, null, null, null, null, 0, null, null, 0, 0, null, null, null, null, null, null, null, null);
    }
}