package org.telestion.mavlink.messages.mavlink.common;

import org.telestion.adapter.mavlink.annotation.MavField;
import org.telestion.adapter.mavlink.annotation.MavInfo;
import org.telestion.adapter.mavlink.annotation.NativeType;
import org.telestion.adapter.mavlink.annotation.MavArray;
import org.telestion.adapter.mavlink.message.MavlinkMessage;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Data for filling the OpenDroneID System message. The System Message contains general system information including the operator location and possible aircraft group information.</br>
 * </br>
 * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
 * 
 * @author Autogenerated by XML2Record-Tool (by Cedric Boes)
 * @version 1.0 (autogenerated)
 * @deprecated This is still WIP and might change!
 */
@Deprecated
@MavInfo(id = 12904, crc = 203)
@SuppressWarnings("preview")
public record OpenDroneIdSystem(
        /**
         * System ID (0 for broadcast).</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.UINT_8)
        @JsonProperty int targetSystem, 
        /**
         * Component ID (0 for broadcast).</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.UINT_8)
        @JsonProperty int targetComponent, 
        /**
         * Only used for drone ID data received from other UAs. See detailed description at https://mavlink.io/en/services/opendroneid.html. </br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavArray(length = 20)
        @MavField(nativeType = NativeType.UINT_8)
        @JsonProperty int[] idOrMac, 
        /**
         * Specifies the operator location type.</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.UINT_8)
        @JsonProperty int operatorLocationType, 
        /**
         * Specifies the classification type of the UA.</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.UINT_8)
        @JsonProperty int classificationType, 
        /**
         * Latitude of the operator. If unknown: 0 (both Lat/Lon).</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.INT_32)
        @JsonProperty int operatorLatitude, 
        /**
         * Longitude of the operator. If unknown: 0 (both Lat/Lon).</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.INT_32)
        @JsonProperty int operatorLongitude, 
        /**
         * Number of aircraft in the area, group or formation (default 1).</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.UINT_16)
        @JsonProperty int areaCount, 
        /**
         * Radius of the cylindrical area of the group or formation (default 0).</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.UINT_16)
        @JsonProperty int areaRadius, 
        /**
         * Area Operations Ceiling relative to WGS84. If unknown: -1000 m.</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.FLOAT)
        @JsonProperty double areaCeiling, 
        /**
         * Area Operations Floor relative to WGS84. If unknown: -1000 m.</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.FLOAT)
        @JsonProperty double areaFloor, 
        /**
         * When classification_type is MAV_ODID_CLASSIFICATION_TYPE_EU, specifies the category of the UA.</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.UINT_8)
        @JsonProperty int categoryEu, 
        /**
         * When classification_type is MAV_ODID_CLASSIFICATION_TYPE_EU, specifies the class of the UA.</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.UINT_8)
        @JsonProperty int classEu) implements MavlinkMessage {
    /**
     * There shall be no default-constructor for normal developers.
     */
    @SuppressWarnings("unused")
    private OpenDroneIdSystem() {
        this(0, 0, null, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
    }
}