package org.telestion.mavlink.messages.mavlink.matrixpilot;

import org.telestion.adapter.mavlink.annotation.MavField;
import org.telestion.adapter.mavlink.annotation.MavInfo;
import org.telestion.adapter.mavlink.annotation.NativeType;
import org.telestion.adapter.mavlink.message.MavlinkMessage;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Backwards compatible version of SERIAL_UDB_EXTRA F22 format</br>
 * </br>
 * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
 * 
 * @author Autogenerated by XML2Record-Tool (by Cedric Boes)
 * @version 1.0 (autogenerated)
 */
@MavInfo(id = 188, crc = 91)
@SuppressWarnings("preview")
public record SerialUdbExtraF22(
        /**
         * SUE X accelerometer at calibration time</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.INT_16)
        @JsonProperty int sueAccelXAtCalibration, 
        /**
         * SUE Y accelerometer at calibration time</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.INT_16)
        @JsonProperty int sueAccelYAtCalibration, 
        /**
         * SUE Z accelerometer at calibration time</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.INT_16)
        @JsonProperty int sueAccelZAtCalibration, 
        /**
         * SUE X gyro at calibration time</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.INT_16)
        @JsonProperty int sueGyroXAtCalibration, 
        /**
         * SUE Y gyro at calibration time</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.INT_16)
        @JsonProperty int sueGyroYAtCalibration, 
        /**
         * SUE Z gyro at calibration time</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.INT_16)
        @JsonProperty int sueGyroZAtCalibration) implements MavlinkMessage {
    /**
     * There shall be no default-constructor for normal developers.
     */
    @SuppressWarnings("unused")
    private SerialUdbExtraF22() {
        this(0, 0, 0, 0, 0, 0);
    }
}