package org.telestion.mavlink.messages.mavlink.matrixpilot;

import org.telestion.adapter.mavlink.annotation.MavField;
import org.telestion.adapter.mavlink.annotation.MavInfo;
import org.telestion.adapter.mavlink.annotation.NativeType;
import org.telestion.adapter.mavlink.message.MavlinkMessage;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Backwards compatible version of SERIAL_UDB_EXTRA F4: format</br>
 * </br>
 * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
 * 
 * @author Autogenerated by XML2Record-Tool (by Cedric Boes)
 * @version 1.0 (autogenerated)
 */
@MavInfo(id = 172, crc = 191)
@SuppressWarnings("preview")
public record SerialUdbExtraF4(
        /**
         * Serial UDB Extra Roll Stabilization with Ailerons Enabled</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.UINT_8)
        @JsonProperty int sueRollStabilizationAilerons, 
        /**
         * Serial UDB Extra Roll Stabilization with Rudder Enabled</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.UINT_8)
        @JsonProperty int sueRollStabilizationRudder, 
        /**
         * Serial UDB Extra Pitch Stabilization Enabled</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.UINT_8)
        @JsonProperty int suePitchStabilization, 
        /**
         * Serial UDB Extra Yaw Stabilization using Rudder Enabled</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.UINT_8)
        @JsonProperty int sueYawStabilizationRudder, 
        /**
         * Serial UDB Extra Yaw Stabilization using Ailerons Enabled</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.UINT_8)
        @JsonProperty int sueYawStabilizationAileron, 
        /**
         * Serial UDB Extra Navigation with Ailerons Enabled</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.UINT_8)
        @JsonProperty int sueAileronNavigation, 
        /**
         * Serial UDB Extra Navigation with Rudder Enabled</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.UINT_8)
        @JsonProperty int sueRudderNavigation, 
        /**
         * Serial UDB Extra Type of Alitude Hold when in Stabilized Mode</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.UINT_8)
        @JsonProperty int sueAltitudeholdStabilized, 
        /**
         * Serial UDB Extra Type of Alitude Hold when in Waypoint Mode</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.UINT_8)
        @JsonProperty int sueAltitudeholdWaypoint, 
        /**
         * Serial UDB Extra Firmware racing mode enabled</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.UINT_8)
        @JsonProperty int sueRacingMode) implements MavlinkMessage {
    /**
     * There shall be no default-constructor for normal developers.
     */
    @SuppressWarnings("unused")
    private SerialUdbExtraF4() {
        this(0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
    }
}