package org.telestion.mavlink.messages.mavlink.matrixpilot;

import org.telestion.adapter.mavlink.annotation.MavField;
import org.telestion.adapter.mavlink.annotation.MavInfo;
import org.telestion.adapter.mavlink.annotation.NativeType;
import org.telestion.adapter.mavlink.message.MavlinkMessage;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Backwards compatible version of SERIAL_UDB_EXTRA F8: format</br>
 * </br>
 * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
 * 
 * @author Autogenerated by XML2Record-Tool (by Cedric Boes)
 * @version 1.0 (autogenerated)
 */
@MavInfo(id = 176, crc = 142)
@SuppressWarnings("preview")
public record SerialUdbExtraF8(
        /**
         * Serial UDB Extra HEIGHT_TARGET_MAX</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.FLOAT)
        @JsonProperty double sueHeightTargetMax, 
        /**
         * Serial UDB Extra HEIGHT_TARGET_MIN</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.FLOAT)
        @JsonProperty double sueHeightTargetMin, 
        /**
         * Serial UDB Extra ALT_HOLD_THROTTLE_MIN</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.FLOAT)
        @JsonProperty double sueAltHoldThrottleMin, 
        /**
         * Serial UDB Extra ALT_HOLD_THROTTLE_MAX</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.FLOAT)
        @JsonProperty double sueAltHoldThrottleMax, 
        /**
         * Serial UDB Extra ALT_HOLD_PITCH_MIN</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.FLOAT)
        @JsonProperty double sueAltHoldPitchMin, 
        /**
         * Serial UDB Extra ALT_HOLD_PITCH_MAX</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.FLOAT)
        @JsonProperty double sueAltHoldPitchMax, 
        /**
         * Serial UDB Extra ALT_HOLD_PITCH_HIGH</br>
         * </br>
         * <i>Autogenerated by XML2Record-Tool v1.3.7</i>
         */
        @MavField(nativeType = NativeType.FLOAT)
        @JsonProperty double sueAltHoldPitchHigh) implements MavlinkMessage {
    /**
     * There shall be no default-constructor for normal developers.
     */
    @SuppressWarnings("unused")
    private SerialUdbExtraF8() {
        this(0, 0, 0, 0, 0, 0, 0);
    }
}